function Auto(){
    // BITTE DIE PROPS NEHMEN UND ANZEIGEN!!!!!!!!!! ALSO FÜR DUMME
    // OHNE CHATGPT
    // OHNE TUTORIAL
    // HURENSOHN WER REGEL BRICHT
    // BITTE BEI ALTE PROJEKT TODO ABGUCKEN WIE MAN ANZEIGT
    // TIPP: ALS PROP EINFACH DIE ATTRIBUTE DURCHGEBEN UND HIER NEHMEN UND EINFACH MIT HTML AUSGEBEN 
    // BEISPIEL WIR HABEN PROP MARKE GENOMMEN UND GEGEBEN:
    // <h1>{marke}</h1>
    return (
        <h1>Auto</h1>
    )
}


export default Auto